# -*- coding: utf-8 -*-
#
# QGIS Tutorials documentation build configuration file, created by
# sphinx-quickstart on Wed Aug 14 20:19:30 2013.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os
import sphinx_bootstrap_theme 
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.doctest', 'sphinx.ext.intersphinx', 'sphinx.ext.todo', 'sphinx.ext.coverage', 'sphinx.ext.pngmath', 'sphinx.ext.mathjax', 'sphinx.ext.ifconfig', 'sphinx.ext.viewcode']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'QGIS Tutorials and Tips'
copyright = u'2013, Ujaval Gandhi'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = 'v1.0'
# The full version, including alpha/beta/rc tags.
release = '1'

extensions = ['rst2pdf.pdfbuilder']
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False

# -- Internationalization -----------------
locale_dirs = ['../i18n/']   #path is example but recommended.
gettext_compact = False     #optional.

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'bootstrap'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {'bootswatch_theme': 'united',
                      'navbar_pagenav': False,
                      'navbar_site_name': 'Tutorials List'
                     }

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path() 

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = 'QGIS Tutorials and Tips'

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = '../resources/en/docs/common/logo.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
html_sidebars = {
       '**': ['custom_sidebar.html'],
          }

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
html_use_index = False

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'QGISTutorialsdoc'



# -- Options for PDF output --------------------------------------------------
# Grouping the document tree into PDF files. List of tuples
# (source start file, target name, title, author, options).
#
# If there is more than one author, separate them with \\.
# For example: r'Guido van Rossum\\Fred L. Drake, Jr., editor'
#
# The options element is a dictionary that lets you override
# this config per-document.
# For example,
# ('index', u'MyProject', u'My Project', u'Author Name',
# dict(pdf_compressed = True))
# would mean that specific document would be compressed
# regardless of the global pdf_compressed setting.

# List of English langugage tutorials
tutorials_en = [
        ('making_a_map', 'Making A Map'),
        ('working_with_attributes', 'Working with Attributes'),
        ('importing_spreadsheets_csv', 'Importing Spreadsheets or CSV files'),
        ('using_plugins', 'Using Plugins'),
        ('downloading_osm_data', 'Searching and Downloading OpenStreetMap Data'),
        ('basic_vector_styling', 'Basic Vector Styling'),
        ('calculating_line_lengths', 'Calculating Line Lengths and Statistics'),
        ('raster_styling_and_analysis', 'Basic Raster Styling and Analysis'),
        ('raster_mosaicing_and_clipping', 'Raster Mosaicing and Clipping'),
        ('working_with_terrain', 'Working with Terrain Data'),
        ('working_with_wms', 'Working with WMS Data'),
        ('georeferencing_basics', 'Georeferencing Topo Sheets and Scanned Maps'),
        ('advanced_georeferencing', 'Georeferencing Aerial Imagery'),
        ('digitizing_basics', 'Digitizing Map Data'),
        ('performing_table_joins', 'Performing Table Joins'),
        ('performing_spatial_joins', 'Performing Spatial Joins'),
        ('points_in_polygon', 'Points in Polygon Analysis'),
        ('performing_spatial_queries', 'Performing Spatial Queries'),
        ('creating_heatmaps', 'Creating Heatmaps'),
        ('nearest_neighbor_analysis', 'Nearest Neighbor Analysis'),
        ('batch_processing', 'Batch Processing using Processing Framework'),
        ('using_qgis_browser', 'Using the QGIS Browser'),
        ('counting_vertices', 'Counting Number of Vertices in a Layer'),
        ('open_bil_bip_bsq_files', 'Open BIL, BIP or BSQ files in QGIS'),
        ('getting_started_with_pyqgis', 'Getting Started with Python Programming'),
        ('find_neighbor_polygons', 'Find Neighbor Polygons in a Layer'),
        ('leaflet_maps_with_qgis2leaf', 'Leaflet Web Maps with qgis2leaf'),
        ('using_gme_connector', 'Using Google Maps Engine Connector for QGIS'),
        ]
# List of Spanish langugage tutorials
tutorials_es = [
        ('making_a_map', 'Creando un Mapa'),
        ('working_with_attributes', 'Working with Attributes'),
        ('importing_spreadsheets_csv', 'Importación de hojas de cálculo o archivos CSV'),
        ('using_plugins', 'Using Plugins'),
        ('downloading_osm_data', 'Buscando y descargando datos de OpenStreetMap'),
        ('basic_vector_styling', 'Estilos vectoriales básicos'),
        ('calculating_line_lengths', 'Calculating Line Lengths and Statistics'),
        ('raster_styling_and_analysis', 'Basic Raster Styling and Analysis'),
        ('raster_mosaicing_and_clipping', 'Raster Mosaicing and Clipping'),
        ('working_with_terrain', 'Working with Terrain Data'),
        ('working_with_wms', 'Trabajando con información WMS'),
        ('georeferencing_basics', 'Georeferencing Topo Sheets and Scanned Maps'),
        ('advanced_georeferencing', 'Georeferencing Aerial Imagery'),
        ('digitizing_basics', 'Digitizing Map Data'),
        ('performing_table_joins', 'Performing Table Joins'),
        ('performing_spatial_joins', 'Performing Spatial Joins'),
        ('points_in_polygon', 'Points in Polygon Analysis'),
        ('performing_spatial_queries', 'Performing Spatial Queries'),
        ('creating_heatmaps', 'Creating Heatmaps'),
        ('nearest_neighbor_analysis', 'Nearest Neighbor Analysis'),
        ('batch_processing', 'Batch Processing using Processing Framework'),
        ('using_qgis_browser', 'Using the QGIS Browser'),
        ('counting_vertices', 'Counting Number of Vertices in a Layer'),
        ('open_bil_bip_bsq_files', 'Open BIL, BIP or BSQ files in QGIS'),
        ('getting_started_with_pyqgis', 'Getting Started with Python Programming'),
        ('find_neighbor_polygons', 'Find Neighbor Polygons in a Layer'),
        ('leaflet_maps_with_qgis2leaf', 'Leaflet Web Maps with qgis2leaf'),
        ('using_gme_connector', 'Using Google Maps Engine Connector for QGIS'),
        ]
author = 'Ujaval Gandhi'
# We create 2 options dictionaries that let us specify different output paper
# sizes.
a4_options_dict = dict(pdf_stylesheets = ['sphinx','twelvepoint','a4', 'pdf_customstyle'])
letter_options_dict = dict(pdf_stylesheets = ['sphinx','twelvepoint','letter', 'pdf_customstyle'])

language = os.environ.get('LANG')
if language == 'es':
    tutorials = tutorials_es
else:
    tutorials = tutorials_en

pdf_documents = []
for doc_name, doc_title in tutorials:
    pdf_documents.append(
            ('docs/'+ doc_name, doc_name + '_a4', doc_title, author, a4_options_dict))
    pdf_documents.append(
            ('docs/'+ doc_name, doc_name + '_letter', doc_title, author, letter_options_dict))

# PDF options
pdf_style_path = ['.', '_styles', 'source/_styles']
pdf_cover_template = 'pdf_coverpage.tmpl'
pdf_default_dpi = 150
pdf_use_toc = False
pdf_compressed = True
